### ISSUE TITLE
<WorkIcon /> is not defined

### ISSUE THREAD

**Issue by frankstepanski** [stephane-monnot/react-vertical-timeline#100]
Hello

Installed the package but I so not see any reference to <WorkIcon />

Getting error: Uncaught ReferenceError: WorkIcon is not defined

Is there another package to be installed? 

Thanks

**Comment by stephane-monnot** [comment]
Hello,

Yes you need to import icon sets. You also can use your own component.

**Comment by frankstepanski** [comment]
Ok great. Do you have any suggestions for icons that look like your demo?
thanks
