### ISSUE TITLE
How to change icons

### ISSUE THREAD

**Issue by forgyforg** [stephane-monnot/react-vertical-timeline#125]
How do you change the icons? You have `icon={<WorkIcon />}`, but what is WorkIcon? Does it matter what type of file/size? I'm new to react and still not sure how to add images so if you could tell me where the image needs to be included that would be great too!

I put the timeline component and code in the src directory of my app and included this at the top of the file using timeline: `const logo = './logo.ico'`
Then in each VerticalTimelineElement, I do this for icon prop 
```
<VerticalTimelineElement
    icon={logo}
>
```
but when I look at where logo should be on browser, I just see the a string with the logos path:

![Screenshot from 2021-10-22 15-31-37](https://user-images.githubusercontent.com/92890162/138525308-de33ea56-338d-4951-a3da-cfe12b3b5bf4.png)

**Comment by stephane-monnot** [comment]
If your image is not in the public folder, it's normal. 

You need to import your image if you want to use it. 

https://stackoverflow.com/questions/39999367/how-do-i-reference-a-local-image-in-react
