### ISSUE TITLE
[QUESTION] Conflict when using vertical-timeline with react-scroll

### ISSUE THREAD

**Issue by oliviercperrier** [stephane-monnot/react-vertical-timeline#13]
I am using react-vertical-timeline with react-scroll, but it seems like i am having a conflict between the 2 components.

When i click on a scroll Link, the page stop scrolling in the middle of the vertical-timeline.
But, if i load the page and i scroll to the bottom (So i have displayed the entire content of the page) then the scroll links will work perfectly..

Anyone already had this issue??

Thanks

**Comment by stephane-monnot** [comment]
Can you provide an online example ?
Maybe, it's a conflict with react-visibility-sensor ?

**Comment by oliviercperrier** [comment]
Yes sure, you can take a look at my site.

If you click on skills after loading the page, it will stop before the anchor..

www.oliviercastroperrier.com

Thanks!

**Comment by stephane-monnot** [comment]
And I use scroll link on my website without issues : 
https://stephanemonnot.com/

**Comment by oliviercperrier** [comment]
Oh wow! it is working now! 
 
Thank you! Really appreciated :P

**Comment by stephane-monnot** [comment]
Glad to hear that ;) . And good job for your work.

**Comment by oliviercperrier** [comment]
Thanks!!
