### ISSUE TITLE
[QUESTION] Conflict with mobile navbar..

### ISSUE THREAD

**Issue by oliviercperrier** [stephane-monnot/react-vertical-timeline#14]
Hey!

In mobile, when the timeline element appear on screen during scrolling, my navbar is bugging and i cannot find why..

Can you help me please? :/

Here is my site:
www.oliviercastroperrier.com

**Comment by stephane-monnot** [comment]
Maybe you can use Stackoverflow for your problem and add more information about your problem.

**Comment by oliviercperrier** [comment]
I will, but i asked here because i found out that when i disable the animation (animate = false), everything is fine..
