### ISSUE TITLE
React 18 test issue

### ISSUE THREAD

**Issue by 72gm** [stephane-monnot/react-vertical-timeline#144]
Hi,

I seem to have an issue when writing a simple test for the timeline... I only noticed it after upgrading to react 18 (may have been there in 17)

![image](https://user-images.githubusercontent.com/12847881/166484377-1ba00d18-8d8e-42ee-bbe1-25cc210cce1a.png)

Any ideas how i'd fix this? I see that the timeline uses intersection observer but I've never heard of this

**Comment by stephane-monnot** [comment]
Sorry for the delay. You can propose a PR if you want.
