### ISSUE TITLE
Content and Date are not alternating

### ISSUE THREAD

**Issue by kahme022** [stephane-monnot/react-vertical-timeline#145]
Hello,

I am making a portfolio site, and I got the timeline component working but for some reason, the date and content are not alternating from left to right. Has anyone seen this before and know the fix?

![image](https://user-images.githubusercontent.com/31967255/192122144-5bdcc188-0f9a-4713-ae03-9a2a47e66e74.png)

**Comment by stephane-monnot** [comment]
No sorry. If you can, send a link.
