### ISSUE TITLE
[REQUEST] Add types definition

### ISSUE THREAD

**Issue by dacevedo12** [stephane-monnot/react-vertical-timeline#15]
any plans on supporting typescript?

someone made an implementation but it's not actively mantained (currently stuck on 2.0.5) https://github.com/simonefonda/react-vertical-timeline-types/blob/master/index.d.ts

**Comment by stephane-monnot** [comment]
I don't have time this month, but I will check it later.
If you want to contribute, you are welcome. :)

**Comment by stephane-monnot** [comment]
It has been merged.
