### ISSUE TITLE
change lineColor for tailwind dark mode

### ISSUE THREAD

**Issue by ksnirob** [stephane-monnot/react-vertical-timeline#159]
@stephane-monnot @avgupta456 @alex-pex  @nostalgiaz @loun4 @axle-h

Hi, there  is a prop to change the line color. inside the element we can change the color of line by using lineColor="#fff" 
but, i need to change line color for dark mode. how can i change the color using tailwind.

**Comment by architsangal** [comment]
Any updates on this issue? Facing the same problem.

**Comment by ksnirob** [comment]
@architsangal I solved the issue this way, 
`<VerticalTimeline

className="[--line-color: theme (colors.blue.600)] dark: [--Line-color: theme (colors.black.500)]"

lineColor="var (--line-color}"`

you can have your own color.
