### ISSUE TITLE
Vertical time elements not rendering from map function

### ISSUE THREAD

**Issue by barbulescualex** [stephane-monnot/react-vertical-timeline#17]
```
 constructTimeLine = () =>{
        return(
            <VerticalTimeline>
                {this.progressArray.map((object,i)=>
                    <VerticalTimelineElement
                        key={i}
                        className="vertical-timeline-element--work"
                        style={{backgroundColor:object.color}}
                        iconStyle={{ background: 'rgb(33, 150, 243)', color: '#fff' }}
                        date="2011 - present"
                    >
                    <p>
                   {object.comments}
                    </p>
                    </VerticalTimelineElement>
                    )
                }
            </VerticalTimeline> 
        )
    }
    render(){
       return(
            <div>
                <Header
                name={this.state.name}
                imgUrl={this.state.profileImgUrl}
                />
                {this.constructTimeLine()}
            </div>
       )
    }
```

I call constructTimeLine() which returns the Vertical Timeline with a map to render the elements. So the elements themselves will not render, it remains empty. If I add the style for the background color to the element it renders the div with the background color but no text will render. No icon, no date and no text in the timeline element.

**Comment by stephane-monnot** [comment]
Could you provide a full example please ?

**Comment by barbulescualex** [comment]
```
import React from 'react';
import firebase from './Firebase';
import Cookies from 'universal-cookie';
import { VerticalTimeline, VerticalTimelineElement }  from 'react-vertical-timeline-component';
import 'react-vertical-timeline-component/style.min.css';

import Header from './Header';

export default class LoginPage extends React.Component {
    constructor(props){
        super(props);
        this.state = {
            userID: null,
            profileImgUrl: null,
            name: null,
            isDoneLoadingData: false
        }
        this.progressArray = [];
    }

    componentWillMount(){
        let that = this;
        firebase.auth().onAuthStateChanged(function(user) {
            if (user) {
                let userID = firebase.auth().currentUser.uid;
                console.log(userID);
                let cookies = new Cookies();
                let profileImgUrl = (cookies.get('profileImgUrl',{doNotParse:true}));
                let name = (cookies.get('name',{doNotParse:true}));
                that.setState({userID: userID, profileImgUrl: profileImgUrl, name: name},()=>{
                    console.log(this.state);
                    that.fetchProgressData();
                });
            } else {
              console.log('user not signed in');
              his.props.history.replace('/progress');
            }
        });
    }

    fetchProgressData = () => {
        let ref = firebase.database().ref('users/' + this.state.userID + '/progress')
        ref.on('value', (snapshot)=>{
            console.log(snapshot.val())
            snapshot.forEach((childSnapshot)=>{
                console.log(childSnapshot.val());
                this.progressArray.push(childSnapshot.val());
                this.setState({isDoneLoadingData: true});
            })
        });
       
    }

    constructTimeLine = () =>{
        return(
            this.progressArray.map((object,i) => {
                console.log('test')
                return (
                    <VerticalTimelineElement
                    key={i}
                    style={{visibility:'visible', height:'200px'}}
                    iconStyle={{ background: object.color, color: '#fff' }}
                    date={object.date}
                    position='right'
                    >
                        <div>
                            <div style={{display:'flex'}}>
                                {object.imageUrls.map((url,i)=>{
                                    return(
                                        <img key={i} src={url} style={{width:'50px', height:'50px',marginRight:'5px',borderRadius:'3px'}}></img>
                                    )
                                })
                                }
                            </div>
                            <p style={{color:'green'}}>{object.comments}</p>
                        </div>
                    </VerticalTimelineElement>
                );
            })
        )
    }

    render(){
       return(
            <div>
                <Header
                name={this.state.name}
                imgUrl={this.state.profileImgUrl}
                />
                {this.state.isDoneLoadingData&&
                    <VerticalTimeline>
                        {this.constructTimeLine()}
                    </VerticalTimeline> 
                }
            </div>
       )
    }
}
```

This is the page that gets rendered using react-router. I have barebones styling as I'm building out functionality first, turns out the issue was with react-visibility, I have no clue why it was getting called and hidding all the VerticalTimeLineElements but I have commented it out in your ./dist-es6/VerticalTimeLineElement.js 


```
  _createClass(VerticalTimelineElement, [{
    key: 'onVisibilitySensorChange',
    value: function onVisibilitySensorChange(isVisible) {
      //if (isVisible) {
        this.setState({ visible: true });
      //}
    }
  }, {
```

**Comment by Shubham-luv2code** [comment]
I'm working on this mapping the elements of timeline today. It doesn't populate the elements for me.
`getIconClass(val) {
        var iconClass = '';
        switch (val) {
            case 'initialize':
                iconClass = "fa fa-3x fa-hourglass-start"
                break;
            case 'progress':
                iconClass = "fa fa-3x fa-caret-square-o-down"
                break;
            case 'email':
                iconClass = "fa fa-3x fa-envelope"
                break;
            case 'end':
                iconClass = "fa fa-3x fa-hourglass-end"
                break;
            default:
                iconClass = "fa fa-3x fa-caret-square-o-down"
                break;

        }
        return iconClass;
    }
    renderTimelineElements() {
        const { apiRes } = this.state;
        apiRes.StaticWorkflowRes.forEach((element, ind) => {
            if (element.reqType === this.props.reqTypeId) {
                element.steps.map((eleMap, ind) => {
                    var iconClass = this.getIconClass(eleMap.stepType);
                    return (
                    <VerticalTimelineElement
                        key={ind}
                        className="vertical-timeline-element"
                        contentStyle={{ background: 'rgb(33, 150, 243)', color: '#fff' }}
                        contentArrowStyle={{ borderRight: '7px solid  rgb(33, 150, 243)' }}
                        date={`Step ${ind + 1}`}
                        iconStyle={{ background: 'rgb(33, 150, 243)', color: '#fff' }}
                        icon={<i className={iconClass}
                            style={{
                                'position': 'absolute',
                                'right': '11px',
                                'top': '10px'
                            }}></i>}
                    >
                        <div>
                            <h3 className="vertical-timeline-element-title">{eleMap.titleVal}</h3>
                            <h4 className="vertical-timeline-element-subtitle">{eleMap.subtitleVal}</h4>
                            <p>{eleMap.stepDesc}</p>
                        </div>
                    </VerticalTimelineElement>
                    )
                })
            }
        });
    }
    render() {
        return (
            <React.Fragment>
                <VerticalTimeline animate={true}>
                    {this.renderTimelineElements()}
                </VerticalTimeline>
            </React.Fragment>
        )
    }`

**Comment by madhusportIT** [comment]
while i'm using VerticalTimelineElement component .vertical-timeline--animate .vertical-timeline-element-icon.is-hidden { visibility: hidden } this class name is coming and making the section hidden

**Comment by wilbertcaba** [comment]
> while i'm using VerticalTimelineElement component .vertical-timeline--animate .vertical-timeline-element-icon.is-hidden { visibility: hidden } this class name is coming and making the section hidden

I think this is the intended functionality, since the purpose is to animate the timeline when it is in view using, I supposse, Intersection Oberver which should change the element to adding `visibility: visible`, but it it's not changing it for me as well, so I guess the Intersection Observer is not kicking in to display my <VerticalTimelineElement>'s.

@madhusportIT Did you find a solution to this?

**Comment by madhusportIT** [comment]
Hi @wilbertcaba use visible={true} props inside of the VerticalTimelineElement Element

**Comment by wilbertcaba** [comment]
> Hi @wilbertcaba use visible={true} props inside of the VerticalTimelineElement Element

@madhusportIT Thanks for the tip. That effectively makes the `<VerticalTimelineElement>` visible, but then I loose the animation once the elements are in view. These animations are enabled by `intersectionObserverProps={{ rootMargin: "0px 0px 40px 0px" }}` when the `<VerticalTimeline>` enters the viewport, I guess only when `visible={false}`.

@stephane-monnot Any thoughts?

**Comment by madhusportIT** [comment]
@wilbertcaba  but in my case the animation is working

**Comment by wilbertcaba** [comment]
@madhusportIT  do you have the timeline above the fold?

If the timeline is in the viewport (or above the fold) when the page is loaded, the animation works for me as well. If the timeline is not in the viewport, the animation works as well, but by the time I scroll down to the timeline the animation has already been executed so I don't get to see it.

Anyways, I was using Next.js 14.1.0 and I could do some magic tricks to make it work by creating a component for the `<VerticalTimelineElement>` and importing and using it within `<VerticalTimeline>`. But, I ended up downgrading to Next,js 13 (not my desired outcome) which also worked for me by using it as intended (as seen in the Docs) without having to use `visible={true}` props.
