### ISSUE TITLE
[Enhancement] "bounce-out" elements on scrolling up again

### ISSUE THREAD

**Issue by PhilippGoetz1995** [stephane-monnot/react-vertical-timeline#184]
Currently the elements are only "bounce-in" on scrolling down => would be really great if there is also an option that the elements are bouncing out on scrolling up again

**Comment by stephane-monnot** [comment]
If you want the same effect on scroll up : https://stephane-monnot.github.io/react-vertical-timeline/#/demo-effect

You can do : 
```jsx
<VerticalTimelineElement
    intersectionObserverProps={{
      rootMargin: '0px 0px -40px 0px',
      triggerOnce: false,
    }}
...
```

**Comment by PhilippGoetz1995** [comment]
@stephane-monnot  - Amazing thanks for that fast support!
