### ISSUE TITLE
Single column on desktop

### ISSUE THREAD

**Issue by nostalgiaz** [stephane-monnot/react-vertical-timeline#20]
Hello there and congratulations for this library! It's amazing! 

What about a new prop that allows us to render the component in a single column instead of using two? In other words: mobile layout on desktop.

Let me know 👍

**Comment by stephane-monnot** [comment]
Hello Nostalgiaz.
Good idea. I think we can add a `layout` prop on VerticalTimeline to manage it. 
`2-columns`, `1-column-left`, `1-column-right`.
What do you think about it ?

**Comment by nostalgiaz** [comment]
Hello!
Sounds good to me! Keep in mind that you have a `position` prop that can be useless if `1-column-*` is set.

**Comment by stephane-monnot** [comment]
Yes, I know. Maybe we can add a help text in the documentation.

**Comment by nostalgiaz** [comment]
And maybe raise an error if it’s set :)

**Comment by stephane-monnot** [comment]
You can develop this feature and make a PR. Or I will develop in the next few weeks

**Comment by nostalgiaz** [comment]
#21

**Comment by nostalgiaz** [comment]
Did in: https://github.com/stephane-monnot/react-vertical-timeline/pull/21
