### ISSUE TITLE
i am geting error in icon 

### ISSUE THREAD

**Issue by atuljustano** [stephane-monnot/react-vertical-timeline#25]
The component is awesome but it wants some updates to do that 
i m getting this error

./src/views/History/History.js
Module not found: Can't resolve '@material-ui/icons' in 'E:\ex\coreui-client\src\views\History'

**Comment by stephane-monnot** [comment]
Maybe you need to add to your package.json the '@material-ui/icons' dependencies.
You can find an example here : 
https://github.com/stephane-monnot/resume/blob/master/package.json

Indeed, the dependence material ui is not part of `react-vertical-timeline` package.

**Comment by atuljustano** [comment]
add I done that nothing is happening you just forget it I'll manage it by
my own it's information for you

**Comment by atuljustano** [comment]
I also tried that one :(
