### ISSUE TITLE
Documentation error 

### ISSUE THREAD

**Issue by ShiraNeuman** [stephane-monnot/react-vertical-timeline#26]
Hi, I saw an error in the documentation about the layout prop. It's written in the explanation under- 
"Choose if you want 'one-column' or 'two-columns' (default: 'two-columns'). " 
but in the code, the props options are 1-column and 2-columns.
So it writes a warning and also if you will write two-columns it won't work (it will do one column).
I have no problem changing it on my own but I don't know if you prefer to change the documentation or the code itself. 

![image](https://user-images.githubusercontent.com/46919790/51531499-470ba400-1e46-11e9-957d-f03ddff17e31.png)

**Comment by Snaptags** [comment]
The TypeScript definitions use the variant used in the screenshot, too:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-vertical-timeline-component/index.d.ts
I.e. the documentation should be changed, not the code.

**Comment by stephane-monnot** [comment]
Thank you ! I fixed it
