### ISSUE TITLE
Styling doesnt work

### ISSUE THREAD

**Issue by shadowae** [stephane-monnot/react-vertical-timeline#28]
Div is all miss aligned and style is messed up. Please help.

**Comment by stephane-monnot** [comment]
Maybe related to #3  ?

**Comment by shadowae** [comment]
yes.

**Comment by shadowae** [comment]
<img width="1437" alt="screenshot 2019-01-29 at 10 32 24 pm" src="https://user-images.githubusercontent.com/10102091/51915329-d2240580-2415-11e9-8138-9ac894c7304f.png">
This is the best i get which makes the date still misalign between the left aligned date and right aligned date.

**Comment by jinman** [comment]
I have found the same issue. Any ideas how to fix it?

**Comment by twhite96** [comment]
Yeah I tried all the tricks in issue #3 and nothing is working...

**Comment by twhite96** [comment]
Got it. Changed my background color.
