### ISSUE TITLE
Date Overlaps with Icon and iconStyle's color has no effect

### ISSUE THREAD

**Issue by Laziemo** [stephane-monnot/react-vertical-timeline#29]
Hey Stephane

Firstly, Cheers for the beautiful work! 

The issue I've been facing is with the date text. With every alternate VerticalTimelineElement the date text overlaps with the Icon (when the date is to the left and content to the right). 

Also, in the following setting: 
iconStyle={{ background: 'rgb(237, 123, 53)', color: '#11287f' }}

color seems to have no effect on the icon.

**Comment by stephane-monnot** [comment]
Could you provide a full example please ? screenshots ?

**Comment by Laziemo** [comment]
`import React, {Component} from 'react';
import { VerticalTimeline, VerticalTimelineElement }  from 'react-vertical-timeline-component';
import 'react-vertical-timeline-component/style.min.css';

const VALUES = [ "2019-04-01","2019-07-01","2019-10-01","2020-01-01"];

class Operations extends Component{

  render(){
    return(
      <div>
        <div className='Headings'>
        <hr />
        <h2> Timeline </h2>
        <hr />
        </div>
        <div>
          <VerticalTimeline>
            <VerticalTimelineElement
              className="vertical-timeline-element--work"
              date="2019: April-July"
              iconStyle={{ background: 'rgb(237, 123, 53)', color: '#11287f' }}
              animate="true"
              style = {{margin:"100px"}}
              >
              <h3 className="vertical-timeline-element-title">Init</h3>
              <p>
              </p>
            </VerticalTimelineElement>

            <VerticalTimelineElement
              className="vertical-timeline-element--work"
              date="July-October"
              iconStyle={{ background: 'rgb(145, 237, 53)', color: '#11287f' }}
              animate="true"

              >
              <h3 className="vertical-timeline-element-title">Finding a rhythm</h3>
              <p>
              </p>
            </VerticalTimelineElement>

            <VerticalTimelineElement
              className="vertical-timeline-element--work"
              date="October-December"
              iconStyle={{ background: 'rgb(53, 237, 229)', color: '#11287f' }}
              animate="true"
              >
              <h3 className="vertical-timeline-element-title">Pick up the tempo</h3>
              <p>
              </p>
            </VerticalTimelineElement>

            <VerticalTimelineElement
              className="vertical-timeline-element--work"
              date="2020: January onwards"
              iconStyle={{ background: 'rgb(111, 34, 171)', color: '#11287f' }}
              animate="true"
              >
              <h3 className="vertical-timeline-element-title">Go for Gold!</h3>
              <p>
              </p>
            </VerticalTimelineElement>

          </VerticalTimeline>
          </div>
      </div>
    );
  }
}

export default Operations;`

**Comment by Laziemo** [comment]
https://ufile.io/43jl7

**Comment by Laziemo** [comment]
Github is rendering parts of the code im pasting. 

Uploaded to uploadfiles.io as a .txt

https://ufile.io/n4njc

**Comment by stephane-monnot** [comment]
I think the problem is likely due to box-sizing: border-box

Maybe related to this issue : #3
