### ISSUE TITLE
the style is weird,pls help me

### ISSUE THREAD

**Issue by Tangyiming** [stephane-monnot/react-vertical-timeline#3]
```
import React, { Component } from 'react';
import { httpRequest } from '../../util/network';
import { VerticalTimeline, VerticalTimelineElement } from 'react-vertical-timeline-component';
import 'react-vertical-timeline-component/style.min.css';
import { Icon } from 'antd';

export default class AboutUs extends Component {
    constructor(props) {
        super(props);
        this.state = {
            info: []
        }

    }

    componentWillMount() {
        this.getAboutUsInfo();
    }

    getAboutUsInfo() {
        httpRequest({
            url: HOST_IP + 'api-perf-load-rest/system/aboutus',
            method: 'GET',
            credentials: 'include',
            headers: {
                "content-type": 'application/json',
            },
        }, (response) => {
            this.setState({ info: !!response.value ? response.value : [] });
        }, (response) => {
            this.setState({ info: [] });
        })
    }

    render() {
        return (
            <div>
                <div style={{margin:"10px 0px 10px 10px"}}>

                    关于我们

                </div>
                <div className="break-line"></div>
                <div>
                    <div style={{ textAlign: "center", margin: "10px 0px 10px 0px" }}><font size="6">我们是谁?</font></div>
                    <div style={{ textAlign: "center", margin: "10px 0px 10px 0px" }}><font size="3">
                        <div style={{ margin: "4px 0px 10px 0px" }}>性能测试平台是红星平台保障部门出品的性能测试服务平台</div>
                        <div style={{ margin: "4px 0px 10px 0px" }}>它服务于公司所有的C，B，E端产品，致力于产品的性能把控和质量提升。</div>
                        <div style={{ margin: "4px 0px 10px 0px" }}>性能测试服务平台包含接口压测，查看压测结果和压测报告，以及查看生产上的应用,组件和接口的消费指数。</div>
                    </font></div>
                    <div style={{ textAlign: "center", margin: "50px 0px 10px 0px" }}><font size="6">我们的历程</font></div>

                    <VerticalTimeline>
                        <VerticalTimelineElement
                            className="vertical-timeline-element--work"
                            date="2011 - present"
                            iconStyle={{ background: 'rgb(33, 150, 243)', color: '#fff' }}
                            icon={<Icon type="smile-o" />}
                        >
                            <h3 className="vertical-timeline-element-title">Creative Director</h3>
                            <h4 className="vertical-timeline-element-subtitle">Miami, FL</h4>
                            <p>
                                Creative Direction, User Experience, Visual Design, Project Management, Team Leading
                            </p>
                        </VerticalTimelineElement>
                    </VerticalTimeline>
                </div>
            </div>
        )
    }

```

this is my code ,and looks like this:
![_20180104174622](https://user-images.githubusercontent.com/18328731/34558044-6790070e-f177-11e7-8ff8-f134e6acdfff.png)

**Comment by stephane-monnot** [comment]
Have you tried to remove all your own stylesheets ? Could you provide a complete example / link ?

**Comment by Tangyiming** [comment]
@stephane-monnot 
first of all,thank you for your patient help. well,the problem still there.
1.i removed all my stylesheet
2.i commented the icon configuration
![Uploading 屏幕快照 2018-01-04 下午8.50.01.png…]()

3.i can see the styles you mentioned above
<img width="1089" alt="2018-01-04 8 49 21" src="https://user-images.githubusercontent.com/18328731/34564313-232d701e-f191-11e7-9714-00381e881eef.png">

and then i don't know where is the problem.can you give me the code of your demo?thank you

**Comment by Tangyiming** [comment]
<img width="1136" alt="2018-01-04 9 14 03" src="https://user-images.githubusercontent.com/18328731/34565699-cd2d350e-f196-11e7-8971-1689d20cfb85.png">
@stephane-monnot 
i change this property to 45%,seems solves problem,maybe i need overive the default style sheet

thank you !!!

**Comment by stephane-monnot** [comment]
You can find the code of my demo here : 
https://github.com/stephane-monnot/react-vertical-timeline/tree/master/docs
or a real usecase on my online resume (https://webエンジニア.com/) here :
https://github.com/stephane-monnot/resume/tree/master/src/components/ResumeProjectsBlock 
and here :
https://github.com/stephane-monnot/resume/tree/master/src/components/ResumeWorkAndEducationBlock
I hope it helps :)

**Comment by joeyparis** [comment]
I just want to add that I am also having this same problem and adjusting the `element-content` width to 44% solves the issue the same way. I don't have much additional context to give but wanted to at least let you know the problem may be affecting others as well. I'll come back if I find another more detailed solution!

**Comment by stephane-monnot** [comment]
I will check it when I have time.

**Comment by shadowae** [comment]
I'm having this exact same error.

**Comment by Tangyiming** [comment]
@shadowae https://github.com/stephane-monnot/react-vertical-timeline/issues/3#issuecomment-355282898 try change the witdh property

**Comment by shadowae** [comment]
Hi, it didn’t help.

Thanks and Regards,
Satish Kumar

**Comment by stephane-monnot** [comment]
Could you provide a link to see your bug ?

**Comment by stephane-monnot** [comment]
You have text-align on your .App class. Remove it.
![image](https://user-images.githubusercontent.com/6066368/52103338-839a8500-2628-11e9-9e32-13fecfdd1f66.png)

**Comment by mohitmohlia** [comment]
Can we change the Circle white outline width ?

**Comment by stephane-monnot** [comment]
Yes, you can with css : 

For example :
```css
.vertical-timeline-element-icon {
    -webkit-box-shadow: 0 0 0 10px white, inset 0 5px 0 rgb(0 0 0 / 8%), 0 3px 0 10px rgb(0 0 0 / 5%);
    box-shadow: 0 0 0 10px white, inset 0 5px 0 rgb(0 0 0 / 8%), 0 3px 0 10px rgb(0 0 0 / 5%);
}
```
