### ISSUE TITLE
Override the css style

### ISSUE THREAD

**Issue by Aalsaif96** [stephane-monnot/react-vertical-timeline#32]
Hi

I try to override the "vertical-timeline::before" to disable it  from the page but I can't do that with simple css class like this

.vertical-timeline-element--work::before {
  content: "";
  position: absolute;
  top: 0;
  left: 18px;
  height: 130%;
  width: 4px;
  background: #fff;
}

please help me if you can

**Comment by stephane-monnot** [comment]
Sorry for the delayed response. Can you provide a example please ?
