### ISSUE TITLE
Lib can't support IE

### ISSUE THREAD

**Issue by bleachdugu** [stephane-monnot/react-vertical-timeline#38]
maybe you should build the release again with babel-polyfill thx

**Comment by rhys-nicholls** [comment]
This also causes an Issue if you're using react-scripts pre 2.0

**Comment by stephane-monnot** [comment]
Actually, I don't have a lot of time to develop because I'm building a company in Japan. But I can review a PR if you submit it. :)

**Comment by stephane-monnot** [comment]
#70
