### ISSUE TITLE
2-Columns Layout doesn't work

### ISSUE THREAD

**Issue by jed326** [stephane-monnot/react-vertical-timeline#42]
Whenever the layout prop is set to {"2-columns"}, either explicitly or by default, the 1-column layout still renders.

See example: https://codesandbox.io/s/stoic-lovelace-x8vxp?fontsize=14&hidenavigation=1&theme=dark

**Comment by SBRKH** [comment]
Hi,
It depend on your resolution. It good for me.

**Comment by stephane-monnot** [comment]
Exactly, if the container width is greater than 1168px, you can see the 2 columns.

**Comment by jed326** [comment]
Ah I see the CodeSandbox works for me whenever I expand the window. I was using Safari on fullscreen and it was only giving me 1 column so the issue must be somewhere in my code. Thanks!
