### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by AniOjha** [stephane-monnot/react-vertical-timeline#43]
How can I use my own images as icons of the timeline (eg. the logo of my institute)?

**Comment by SBRKH** [comment]
You have a props icon={} so you can pass your own icons.

**Comment by stephane-monnot** [comment]
Exactly, you can see an example here : 
https://github.com/stephane-monnot/react-vertical-timeline/blob/master/docs/index.js#L50

**Comment by AniOjha** [comment]
Okay, thanks!

**Comment by AniOjha** [comment]
In the example haven't you used the standard WorkIcon from '@material-ui/icons/Work' ? In what format do I pass in my own images?

**Comment by gihanrcg** [comment]
I was also wondering How can we add our own .jpeg, .png icons.

BTW, awesome component

**Comment by jtela** [comment]
This is how I managed to do it :
`import myLogo from './my-logo.png';`
then in the VerticalTimelineElement component :
`icon={<img src={myLogo} alt="myLogo" />}`
This should also work with jpeg, svg, ...
Hope it helps !

**Comment by MarkusWirth** [comment]
Thanks a lot for your work. How is it possible to change the border color of the round element the icon is integrated?
