### ISSUE TITLE
Question: Can you put informative boxes on both sides?

### ISSUE THREAD

**Issue by msalimbe1** [stephane-monnot/react-vertical-timeline#44]
Hello, I see that you can add boxes to each side of the timeline, but I would like to add boxes to both sides as to be able to make comparisons between events. Something like:
    
```
 ⃞ ┼ ⃞  
 ⃞ ┼ ⃞  
```

Is this possible with this component?

Kind Regards

**Comment by stephane-monnot** [comment]
Actually, it's not possible. But I keep in mind. It's a good idea, I will try to develop it if I have time.
