### ISSUE TITLE
[Question] - Infinite scroll.

### ISSUE THREAD

**Issue by rbgfloripa** [stephane-monnot/react-vertical-timeline#47]
Hi,

I want to use this timeline, but I have many (> 10000) records to display.

Can I load new content as I scroll down a page?     
When you get to the bottom of the content, some function is called and automatically loads new content and appends it to the bottom.

Thanks.

**Comment by stephane-monnot** [comment]
Hi, 
I didn't try, but with visibilitySensorProps, you can pass props to the visibility sensor plugin.
With scrollCheck and  onChange props, you can probably do it.
For more information: https://github.com/joshwnj/react-visibility-sensor

**Comment by rbgfloripa** [comment]
Hi,

I tried. But "onChange" is not triggered.  :-(

**Comment by stephane-monnot** [comment]
I pushed a fix on master branch for onChange param.
