### ISSUE TITLE
WorkIcon doesnt show in my code

### ISSUE THREAD

**Issue by varathar53** [stephane-monnot/react-vertical-timeline#48]
Hi friends

I was trying to put the Workicon in my code I tried also to import but it doesnt work.

I was also trying to add this icon from semantic ui but it doesnt work. Can you please tell how to include this icon in your library?
https://react.semantic-ui.com/elements/icon/

Thanks

**Comment by stephane-monnot** [comment]
Hi,

Thank you for your question. Could you provide an full example ?

**Comment by frankstepanski** [comment]
I installed the component and where do I find <WorkIcon /> in your demo?
