### ISSUE TITLE
Error: Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by gaurav517** [stephane-monnot/react-vertical-timeline#49]
I see following with nextjs:
```
[ error ] /Users/user/Documents/myproject/client/node_modules/react-vertical-timeline-component/style.min.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
```
I copied that file `style.min.css` out of node_modules, but still I see:
```
[ error ] ./src/styles/vertical.timeline.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
```
Can you please suggest something? thanks.

**Comment by stephane-monnot** [comment]
I don't use next. Maybe it's a mistake in your next config. Maybe you need to use `@zeit/next-css` and modify your next.config.js to append `withCSS`

**Comment by gaurav517** [comment]
it was resolved by adding `import 'react-vertical-timeline-component/style.min.css';` to `_app.js` file.
Thanks.
