### ISSUE TITLE
Unexpected token: name (VerticalTimelineElement)

### ISSUE THREAD

**Issue by adirpur** [stephane-monnot/react-vertical-timeline#53]
Hi,
I am trying to use "react-vertical-timeline-component" component and all works well
but when I am trying to minify it using "uglifiy-js" I got this exception:
'Unexpected token: name (VerticalTimelineElement)'

looks like a transpile issue
I use all import options but it still doesn't work including dist-modules and dist-es6
![image](https://user-images.githubusercontent.com/23696272/79429565-55585980-7fd0-11ea-9a5d-c0650ae90293.png)

This is the code:
![image](https://user-images.githubusercontent.com/23696272/79429592-630ddf00-7fd0-11ea-847c-ca8939c1df6b.png)

Can you help?
Thanks,

**Comment by stephane-monnot** [comment]
Hi,
Could you provide a full example please ? 
Thanks,

**Comment by adirpur** [comment]
it is one page from all our project application
is this helps? 
 
`import React from 'react';
import PropTypes from 'prop-types';
import {connect} from 'react-redux';
import {VerticalTimeline, VerticalTimelineElement} from 'react-vertical-timeline-component';
import Spinner from '@mh-core/components/Animations/Spinner/index';

import {getMapDispatchToProps, getMapStateToProps} from '../../../../JS/Services/Billing/Redux/reduxService';

import * as actions from './actions';
import * as selectors from './selectors';

import './index.scss';
import EventCardContent, {
    BENEFIT_TYPE,
    SUPPORT_CALL_TYPE,
    TRANSACTION_TYPE,
} from '../../Pages/AccountInfoTimeline/Components/EventCardContent/index.react';
import EventIcon from '../../Pages/AccountInfoTimeline/Components/EventIcon/index.react';

const propTypes = {
    actions: PropTypes.object,
    timelineInfo: PropTypes.arrayOf(PropTypes.object),
};
const defaultProps = {
    actions: {},
    timelineInfo: [],
};

/**
 * @name AccountInfoTimelineContainer
 * @module SiteUtilities
 *
 * @example <AccountInfoTimelineContainer />
 */
export class AccountInfoTimelineContainer extends React.Component {
    constructor(props) {
        super(props);
    }

    componentDidMount() {
        const accountIdIndex = window.location.search.indexOf('account_id=') + 'account_id='.length;
        const accountId = window.location.search.substring(accountIdIndex);
        this.props.actions.getAccountInfoTimeline(accountId);
    }

    render() {
        const {timelineInfo} = this.props;
        return (
            <VerticalTimeline layout="1-column">
                {timelineInfo && timelineInfo.length > 0 && !timelineInfo[0] ? (
                    <div className="spinner">
                        <Spinner enabled />
                    </div>
                ) : (
                    _.map(timelineInfo, (infoItem, key) => {
                        return (
                            <VerticalTimelineElement
                                className="vertical-timeline-element--work"
                                icon={(
<EventIcon
                                        type={infoItem && infoItem.itemType}
                                        tag={infoItem && infoItem.itemTag}
                                        isFail={infoItem && infoItem.itemData.status === 'Failed'}
/>
)}
                            >
                                <EventCardContent type={infoItem && infoItem.itemType} info={infoItem} />
                            </VerticalTimelineElement>
                        );
                    })
                )}
            </VerticalTimeline>
        );
    }
}

const mapStateToProps = getMapStateToProps(selectors);
const mapDispatchToProps = getMapDispatchToProps(actions);

AccountInfoTimelineContainer.propTypes = propTypes;
AccountInfoTimelineContainer.defaultProps = defaultProps;

export default connect(
    mapStateToProps,
    mapDispatchToProps
)(AccountInfoTimelineContainer);
`

**Comment by stephane-monnot** [comment]
Did you use create react app ? another boilerplate ? the error seems to occur during build stage, so it's better if you  can share the webpack config. A complete project sources is better.

**Comment by adirpur** [comment]
The complete project size is very big
This is the webpack config, hope it will help 

`const ModuleUpdateLogger = require('../ModuleUpdateLogger');

module.exports = (entry, logFile, createStats) => ({
    entry,
    devtool: false,
    output: {
        library: '[name]Server',
        libraryExport: 'default',
        libraryTarget: 'commonjs2',
    },
    target: 'node',
    module: {
        rules: [
            {
                test: /\.scss$/,
                use: 'null-loader',
            },
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: {
                    loader: require.resolve('babel-loader'),
                    options: require('@mh-build/build/babel/server.babel.config'),
                },
            },
        ],
    },
    plugins: [
        new ModuleUpdateLogger('Server', {
            logFile,
            createStats,
        }),
    ],
});
`

**Comment by stephane-monnot** [comment]
Did you fix the problem ?

**Comment by adirpur** [comment]
Hi, I was waiting for an answer/solution from you
The project is currently stuck because of it
Can you help?

**Comment by stephane-monnot** [comment]
Sorry but I can't reproduce the problem. I found a similar issue :
https://github.com/webpack/webpack/issues/2972

**Comment by adirpur** [comment]
Hi, Thanks
According to the issue you sent me, looks like uglify.js doesn’t work with
es6
Did you succeed to use uglify js with the timeline component?
If yes, can you tell how?

**Comment by stephane-monnot** [comment]
Sorry, I don't use uglify.

**Comment by adirpur** [comment]
Any plan to support uglify in this component? Or any workaround?

**Comment by stephane-monnot** [comment]
You can submit a PR if you want to fix it.
