### ISSUE TITLE
onTimelineElementClick handler

### ISSUE THREAD

**Issue by RahulIPEM** [stephane-monnot/react-vertical-timeline#55]
The event handler is not working as I had reinstall all node modules after you have merged and I lost my local changes. And it stopped working. I have gone through VerticalTimelineElement.js and changes are not there. Please check.

**Comment by stephane-monnot** [comment]
Can you check the version in your package.json and package-lock.json please ? 

```shell
 yarn list --pattern=react-vertical-timeline-component
or
npm list react-vertical-timeline-component
```
