### ISSUE TITLE
Can timeline Component Support Pagination?

### ISSUE THREAD

**Issue by subodhcjoshi82** [stephane-monnot/react-vertical-timeline#58]
Hi
Can you please tell if this component support Pagination feature...Suppose i want to load 10 record a time and when click on next then next 10 should load or scrolling down should load next 10 items?

**Comment by stephane-monnot** [comment]
Hi,

You have to implement this feature in your component. 
1. Create a button to load new data
2. Build VerticalTimeline children with a props (ex: records) (Use redux if need)
3. If user clicks on "Load new data" button, add more 10 items to records props.
4. You component will rerender with the additional 10 records.

**Comment by stephane-monnot** [comment]
I added a demo for you ;) : https://stephane-monnot.github.io/react-vertical-timeline/#/demo-load-more

You could use this script as inspiration.

**Comment by subodhcjoshi82** [comment]
Thanks will test and update you further.
