### ISSUE TITLE
VerticalTimeLineColor change issue

### ISSUE THREAD

**Issue by Binz95** [stephane-monnot/react-vertical-timeline#59]
I changed the color of line between each vertical element.... 
The color is black..... 
I face an issue while loading the timeline 
It shows a black line before loading the timeline events...
What should I do for hide this blank black line before  loading my timeline data..

**Comment by stephane-monnot** [comment]
You can hide the line by default and show on scroll. Maybe you can use visibilitySensorProps prop to show the line.

**Comment by Binz95** [comment]
Iam new to this react.... 
After checking iam confused to apply this... Can u pls help me... 😞

**Comment by Binz95** [comment]
Please help me.... 
Iam stuck with this issue 😔

**Comment by stephane-monnot** [comment]
Sorry, I'm in Japan, I was sleeping :D . 

I will  look it now.

**Comment by stephane-monnot** [comment]
I can't reproduce your issue. Could you provide an example ?

**Comment by Binz95** [comment]
![tmp_1588065597255](https://user-images.githubusercontent.com/45253249/80470432-a157b680-895f-11ea-9488-d60183a05fd1.jpg)
 When my spfx webpart load the vertical timeline shows this line default.... 
My timeline should start and end with icon and event.... 
No need to show this black line initially

**Comment by Binz95** [comment]
. verticalTimeLineColor ::before {
background :black! important;
}
I give this style for the line in timeline display 
I need to show it when only the webpart events load
No need to display the line default

**Comment by Binz95** [comment]
![15880658681507566563984601539344](https://user-images.githubusercontent.com/45253249/80470872-35c21900-8960-11ea-8d8f-570d1bf15e0b.jpg)
![15880659190141125767391643925230](https://user-images.githubusercontent.com/45253249/80471026-7326a680-8960-11ea-9ede-ed561ac2a079.jpg)
Iam talking about the black line occured below the drop down.... 
It is from this timeline

**Comment by Binz95** [comment]
If there are no events in timeline then also this black line is appearing in my webpart... 
No need to show this black line while loading

**Comment by stephane-monnot** [comment]
If you have no event, you can add a condition and skip the render of VerticalTimeline : 
```jsx
{events.length > 0 &&
    <VerticalTimeline>....</VerticalTimeline>        
}
```

**Comment by Binz95** [comment]
How to remove the black line after the end of events
![15880698382992335849598805685217](https://user-images.githubusercontent.com/45253249/80477372-72464280-8969-11ea-8529-9cb42911b038.jpg)

See this image

**Comment by Binz95** [comment]
From top I removed 
But I can't remove from bottom

**Comment by stephane-monnot** [comment]
It's not possible.

But with a little hack, you can :) 

Hide the line : 
```css
.vertical-timeline::before {
    background: transparent;
}
```
And create line for each items : 
```css
.vertical-timeline-element:not(:last-child)::before {
    content: '';
    position: absolute;
    top: 30px;
    left: 18px;
    height: calc(100%);
    width: 4px;
    background: white;
}
```

**Comment by Binz95** [comment]
Thank you so much dear stephene 
It's working now 😍

**Comment by Binz95** [comment]
It's working now

**Comment by Binz95** [comment]
My timeline is one column type 
As u mentioned I did 
But now for each event item the vertical timeline component means controller is created 
Before this I called <VerticalTimeline> for once 
Then looped for all items 
<VerticalTimelineElement>
After looping all events I closed </VerticalTimeline>
Now for each event I need to call <VerticalTimeline>
Which takes so much time to load the timeline events

**Comment by Binz95** [comment]
This is my rendering code



This is my style

**Comment by Binz95** [comment]
Style I applied for getting black line 
![1588078348818558971028155355308](https://user-images.githubusercontent.com/45253249/80489316-43d26280-897d-11ea-9781-3ef6b10f540a.jpg)

Rendering  code

![Uploading 15880784115346728601572723655078.jpg…]()

**Comment by Binz95** [comment]
Style I applied for getting black line 
![1588078348818558971028155355308](https://user-images.githubusercontent.com/45253249/80489316-43d26280-897d-11ea-9781-3ef6b10f540a.jpg)

Rendering  code

![Uploading 15880784115346728601572723655078.jpg…]()

**Comment by Binz95** [comment]
![Uploading 15880786541404916761789575114102.jpg…]()

Page rendering code

**Comment by stephane-monnot** [comment]
Could you reupload please, I can't see uploaded image.

**Comment by Binz95** [comment]
![15880865944397825572404503642794](https://user-images.githubusercontent.com/45253249/80504628-fb24a480-8990-11ea-81ee-d99f1c55d93e.jpg)
This is my render code now... 
But it takes more time to display timeline.... 
I need the for each loop inside event VerticalTimeline before timeline element... 
But that time  black line not displaying between events.

**Comment by stephane-monnot** [comment]
I don't understand why you create a verticaltimeline for each elements. You should add your .map inside the VerticalTimeline element and inside the map, create a VerticalTimelineElement.

**Comment by Binz95** [comment]
At first I give as u mentioned but that time I didn't get that black line between vertical elements

**Comment by Binz95** [comment]
At first I add .map inside the VerticalTimeline element and inside the map, created a VerticalTimelineElement. But I can't get that black line between each events.... So I change my code like this.... Please help me to find a solution for this problem

**Comment by stephane-monnot** [comment]
Could you share your code if you project is not condidential ? It's 4 am here, I will go to sleep :)

**Comment by Binz95** [comment]
Sorry i can't share the complete code the image I shared is the portion where I used vertical timeline
Where item in itemcollection is consider as each vertical element in vertical timeline.... 
When page loading... It's takes little seconds for binding each event at that time there is a black line only seen in my page... So I need to hide that black line and also I need the black line after event starts and before event end..... 
This is my requirement.... 
Here I can't hide this black line....

**Comment by Binz95** [comment]
I got it thanku

**Comment by farrukh007** [comment]
I m using map() in React vertical timeline but no component is showing in the browser except the line ☹️
