### ISSUE TITLE
Can we Integrate other Component with Timeline Component?

### ISSUE THREAD

**Issue by subodhcjoshi82** [stephane-monnot/react-vertical-timeline#61]
Hi 
Looking for some more feature like 

- Want to give +/- Button or review Button with each timeline post..Something like Stackoverflow provide.
-Want to add feature like Share/Like/Retweet/Comment etc with each timeline post.

Is this type of flexibility will be available ? or this requirement can be feasible to achieve with your component.

**Comment by stephane-monnot** [comment]
Yes, of course. You can look at my online resume : 
https://stephanemonnot.com/fr/cv.html#Resume-work
and 
https://stephanemonnot.com/fr/cv.html#Resume-projects

And the source code available on github : 
https://github.com/stephane-monnot/resume
