### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by hugoperier** [stephane-monnot/react-vertical-timeline#62]
Hello

I am using your timeline library, but I got a deprecation warning.

I am using React 16.13.1

![image](https://user-images.githubusercontent.com/26797879/80897195-a7022300-8cf6-11ea-9001-c14e7bec6965.png)

Best

**Comment by simon6023** [comment]
Hello,
Same warning, same React version.

**Comment by stephane-monnot** [comment]
I think it's a warning from the VisibilitySensor dependency. Maybe it's better to move to a new library. An issue is open for it :  
https://github.com/stephane-monnot/react-vertical-timeline/issues/63

**Comment by stephane-monnot** [comment]
Maybe you can switch to version 3, and check if you still get this warning.

**Comment by simon6023** [comment]
Yes, seems to be fixed ! No more warning.
Thanks !
