### ISSUE TITLE
Migrate from react-visibility-sensor to react-intersection-observer

### ISSUE THREAD

**Issue by amngupta** [stephane-monnot/react-vertical-timeline#63]
react-visibility-sensor is unmaintained and not designed to be consumed through ESM. joshwnj/react-visibility-sensor#148

react-intersection-observer is maintained and has a hooks API.

https://github.com/thebuilder/react-intersection-observer

**Comment by stephane-monnot** [comment]
If I have time, I will work on it. If you want to submit a PR, you are welcome ;)
