### ISSUE TITLE
How to remove the timeline above the first element and below the last element. 

### ISSUE THREAD

**Issue by joysonprofessional** [stephane-monnot/react-vertical-timeline#64]
<img width="313" alt="Screenshot 2020-05-07 at 7 03 14 PM" src="https://user-images.githubusercontent.com/64456611/81300625-87238400-9095-11ea-9e26-394654cbc10d.png">

**Comment by joysonprofessional** [comment]
Like the image and the same after the last element remove the time line color. That is fine even if it is able to change the color same as bckground so it is not visible.

**Comment by stephane-monnot** [comment]
Did you check this answer : 
https://github.com/stephane-monnot/react-vertical-timeline/issues/59#issuecomment-620538428

**Comment by joysonprofessional** [comment]
Thank you it worked.
