### ISSUE TITLE
Adding documentation for custom line color

### ISSUE THREAD

**Issue by avgupta456** [stephane-monnot/react-vertical-timeline#66]
I was looking to duplicate the effect for changing the vertical line color, and couldn't find documentation anywhere. After digging around, I realized adding a className for the VerticalTimeline component with this CSS (class_name:before {background: black;}) has the desired effect. Is this already in the documentation, or can it be added? Thanks!

**Comment by stephane-monnot** [comment]
You can find examples here : 
https://github.com/stephane-monnot/react-vertical-timeline/tree/master/docs

Maybe we could add to the documentation in the future.

**Comment by a-chris** [comment]
Yes please, I spent two hours trying to figure out how to change the line color before to find this issue

**Comment by trungbui2000** [comment]
Could anyone pinpoint me how to customize the line color, there is no specific examples in the link towards the doc. I wanted my line from white to blue, is there a way to do so?

**Comment by douglasrcjames** [comment]
Bumping this, seems like a pretty common use case to include an example on how to do this, if not adding a prop to the VerticalTimeline component to change the line styling. For others, this is how I did it:

**styles.css:**
`.custom-line:before {background: $blue;}`
**Timeline.js:**
```
<VerticalTimeline className="custom-line">
                    <VerticalTimelineElement>
....
```
