### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by jadelmir** [stephane-monnot/react-vertical-timeline#7]
what is the right way to add an Icon?

**Comment by stephane-monnot** [comment]
You can find an example with material-ui-icons here : 
https://github.com/stephane-monnot/resume/blob/master/src/components/ResumeWorkAndEducationBlock/ResumeWorkAndEducationBlock.js
```jsx

<VerticalTimelineElement
  ...
  icon={<WorkIcon />}
  iconStyle={{background: '#2196f3', color: '#fff'}}
  ...
>
  ...
</VerticalTimelineElement>
```

**Comment by luishgranja** [comment]
> what is the right way to add an Icon?

It looks like the icon prop requires an icon element, either from '@material-ui/icons/' or for example from FontAwesome like this: `icon={<i className='fa fa-map'> </i>}` or any other react or html component, another example [here](https://github.com/stephane-monnot/react-vertical-timeline/issues/43#issuecomment-568190906). Hope this helps.
