### ISSUE TITLE
No date and buttons shown 

### ISSUE THREAD

**Issue by bibinvargheset** [stephane-monnot/react-vertical-timeline#78]
I used the same code as given in the readme.md but when I run it I am not able to see the dates on the timeline as well as the button or its configurations. So where can find corresponding code to the gif file of readme .md .  or where is the documentation about the dates on timeline and those buttons

**Comment by stephane-monnot** [comment]
You can find the source code of the documentation here : 
https://github.com/stephane-monnot/react-vertical-timeline/tree/master/docs
