### ISSUE TITLE
Adding a shape to the timeline

### ISSUE THREAD

**Issue by chaitali-pathak** [stephane-monnot/react-vertical-timeline#79]
Thank you for the great library! 
I am using it to create a timeline which includes 5 stages. I need to add an arrow in the timeline in order to show the direction. Is it possible to add it? 
@stephane-monnot 

-Something like this
![Arrow](https://user-images.githubusercontent.com/64214481/93920118-5c785600-fd2c-11ea-85d3-d1fb1f47de40.png)

Thank you

**Comment by stephane-monnot** [comment]
Maybe you can use custom css to add arrow. You can use the class vertical-timeline-element-icon and add a pseudo-element after or before which contains arrow.
