### ISSUE TITLE
Animation not available on responsive

### ISSUE THREAD

**Issue by giuppiF** [stephane-monnot/react-vertical-timeline#8]
Hello! Your time line is great, is it possible to have animations work on mobile? Thank you.

**Comment by stephane-monnot** [comment]
Actually, no. But if I have time, I will add it.

**Comment by giuppiF** [comment]
Thank you Stephane. I don't think I have enough experience (actually i have no idea why it doesn't work on mobile), but I will try anyway to take a look in the source code.

**Comment by stephane-monnot** [comment]
Check the new version v2.0.7 ;)

**Comment by giuppiF** [comment]
Unbelievable! You are amazing! Thank you very much, it works great.
