### ISSUE TITLE
Deep Linking or setting Starting Index

### ISSUE THREAD

**Issue by GeoffGodwin** [stephane-monnot/react-vertical-timeline#81]
First of all thank you very much for this library, I utilized it during a hack-a-thon just recently!

While working on stretch goals I came up with a deep linking use case and wanted to ask how difficult it would be to pass in an optional starting index to this lib. So if I had say 40 items I could start the view at item 25.

Thanks again!

**Comment by stephane-monnot** [comment]
I'm glad to hear that you utilized it.

I added a new prop `visible` on VerticalTimelineElement to force the visibility.
