### ISSUE TITLE
Dates on the Right Not Aligned

### ISSUE THREAD

**Issue by cantoramann** [stephane-monnot/react-vertical-timeline#87]
I am copying the project to a file with no other CSS / JS component imported. I am having an issue where the dates on the right side are strictly centered. I could not manage it by changing the CSS. Why might this be happening? Thanks!

<img width="1323" alt="Screen Shot 2020-11-20 at 03 18 55" src="https://user-images.githubusercontent.com/46545763/99740215-9329dd00-2adf-11eb-9e42-29e589a4c814.png">

**Comment by tanerdiler** [comment]
It might be affected by style of parent. I had same issue. When I cleaned the style of parent, this issue was disappeared.

**Comment by cantoramann** [comment]
Thank you! I believe that was the issue.

**Comment by mcpenguin** [comment]
To anyone encountering this issue too, check that `text-align` property of your timeline is not set to `center` .

**Comment by woodRock** [comment]
> To anyone encountering this issue too, check that `text-align` property of your timeline is not set to `center` .

Assuming the `VerticalTimeline` component has classname "timeline". The code given below will fix this:

```css
.timeline {
    text-align: left;
}
```
