### ISSUE TITLE
Large unpacked size

### ISSUE THREAD

**Issue by robbienohra** [stephane-monnot/react-vertical-timeline#94]
![Screen Shot 2020-12-17 at 4 02 15 PM](https://user-images.githubusercontent.com/28514482/102543429-4c4cea00-4081-11eb-8baa-79dfa40570f4.png)

Wondering why the unpacked size is so large?

**Comment by stephane-monnot** [comment]
It's fixed : https://www.npmjs.com/package/react-vertical-timeline-component/v/3.3.3
![image](https://user-images.githubusercontent.com/6066368/106085206-18c2ac80-6163-11eb-9bdb-fadb6e20c96f.png)

**Comment by robbienohra** [comment]
Awesome, thanks!
